---
kind: "iac.rcmd.space/multitemplate"
id: "monitoring.checks"
annotations:
  triggers:
    - "monitoring.wtfd.restart"
multitemplate:
  - path: "/etc/monitoring/configs"
    template: "stages/monitoring/templates/check.ini.tmpl"
    config: "stages/monitoring/variables/checks_outpost.yaml"
    extension: "ini"
    mode: "644"
    ownership: "root:root"
