---
kind: "iac.rcmd.space/command"
id: "monitoring.wtfd.restart"
command:
  - createCommand: "systemctl reset-failed wtfd.service && systemctl enable wtfd.service && systemctl restart wtfd.service"
    deleteCommand: "/bin/true"
