---
kind: "iac.rcmd.space/file"
id: "monitoring.wtfd.files"
file:
  - name: "/etc/monitoring/configs"
    mode: "755"
    ownership: "root:root"
    source: "directory"
  - name: "/etc/monitoring/plugins"
    mode: "755"
    ownership: "root:root"
    source: "directory"
  - name: "/etc/monitoring/notifiers"
    mode: "755"
    ownership: "root:root"
    source: "directory"
  - name: "/usr/local/bin/wtf"
    mode: "755"
    ownership: "root:root"
    source: "stages/monitoring/files/bin/wtf"
  - name: "/etc/monitoring/config.ini"
    mode: "644"
    ownership: "root:root"
    source: "stages/monitoring/files/configs/config.ini"
  - name: "/etc/monitoring/plugins"
    mode: "755"
    ownership: "root:root"
    source: "stages/monitoring/files/plugins"
---
kind: "iac.rcmd.space/command"
id: "monitoring.wtfd.restart"
command:
  - createCommand: "systemctl reset-failed wtfd.service && systemctl enable wtfd.service && systemctl restart wtfd.service"
    deleteCommand: "/bin/true"
