---
kind: "iac.rcmd.space/package"
id: "monitoring.wtfd.packages"
package:
  - name: "dafuq"
---
kind: "iac.rcmd.space/directory.v2"
id: "monitoring.wtfd.directories"
directory:
  - name: "/var/www/healthchecks"
    mode: "755"
    ownership: "root:root"
  - name: "/etc/monitoring/configs"
    mode: "755"
    ownership: "root:root"
  - name: "/etc/monitoring/plugins"
    mode: "755"
    ownership: "root:root"
  - name: "/etc/monitoring/notifiers"
    mode: "755"
    ownership: "root:root"
---
kind: "iac.rcmd.space/file.v2"
id: "monitoring.wtfd.core"
annotations:
  triggers:
    - "monitoring.wtfd.restart"
file:
  - name: "/usr/local/bin/wtf"
    mode: "755"
    ownership: "root:root"
    source: "stages/monitoring/files/bin/wtf"
  - name: "/etc/monitoring/config.ini"
    mode: "644"
    ownership: "root:root"
    source: "stages/monitoring/files/configs/config.ini"
  - name: "/etc/systemd/system/wtfd.service"
    mode: "644"
    ownership: "root:root"
    source: "stages/monitoring/files/configs/wtfd-standard.service"
---
kind: "iac.rcmd.space/install.v2"
id: "monitoring.wtfd.plugins"
install:
  - name: "/etc/monitoring/plugins"
    mode: "755"
    ownership: "root:root"
    source: "stages/monitoring/files/plugins"
  - name: "/etc/monitoring/notifiers"
    mode: "755"
    ownership: "root:root"
    source: "stages/monitoring/files/handlers"
---
kind: "iac.rcmd.space/command"
id: "monitoring.wtfd.restart"
command:
  - createCommand: "systemctl reset-failed wtfd.service && systemctl enable wtfd.service && systemctl restart wtfd.service"
    deleteCommand: "/bin/true"
