#!/usr/bin/env bash

set -eo pipefail

IFS=$'\n'

ENTRIES=$(yq -o=json '.command' ${IACD_DOCUMENT} | jq -cRr 'fromjson | .[]')


for entry in $ENTRIES; do
    entry_create=$(echo "${entry}" | jq -Rr 'fromjson | .createCommand')
    entry_delete=$(echo "${entry}" | jq -r 'fromjson | .deleteCommand')

    case ${1} in
        "create" | "update")
            bash -c "${entry_create}"
            ;;
        "delete")
            bash -c "${entry_delete}"
            ;;
        "compare")
            exit 0
            ;;
    esac
done
