#!/usr/bin/env bash

set -eo pipefail

IFS=$'\n'

ENTRIES=$(yq -o=json '.download' ${IACD_DOCUMENT} | jq -cRr 'fromjson | .[]')


for entry in $ENTRIES; do
    entry_destination=$(echo "${entry}" | jq -Rr  'fromjson | .destination')
    entry_url=$(echo "${entry}" | jq -Rr 'fromjson | .url')
    entry_mode=$(echo "${entry}" | jq -Rr 'fromjson | .mode')
    entry_ownership=$(echo "${entry}" | jq -Rr 'fromjson | .ownership')

    case ${1} in
        "create" | "update")
            curl --fail -sL "${entry_url}" > "${entry_destination}"
            chown "${entry_ownership}" "${entry_destination}"
            chmod "${entry_mode}" "${entry_destination}"
            echo "Download ${entry_url} created (or updated)"
            ;;
        "delete")
            rm -f "${entry_destination}"
            echo "Download ${entry_name} deleted"
            ;;
        "compare")
            test -f "${entry_destination}"
            ;;
    esac
done
