---
kind: pipeline
type: exec
name: hangar

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: clone
  commands:
  - git clone $DRONE_GIT_SSH_URL
- name: build
  commands:
  - cd $DRONE_REPO_NAME && sudo make

node:
  machine: hangar.rcmd.space

---
kind: pipeline
type: exec
name: fermium

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: clone
  commands:
  - git clone $DRONE_GIT_SSH_URL
- name: build
  commands:
  - cd $DRONE_REPO_NAME && sudo make fermium

node:
  machine: fermium

---
kind: pipeline
type: exec
name: printserver

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: clone
  commands:
  - git clone $DRONE_GIT_SSH_URL
- name: build
  commands:
  - cd $DRONE_REPO_NAME && sudo make printserver

node:
  machine: orangepizero
