---
kind: pipeline
type: exec
name: hangar

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: clone
  commands:
  - git clone $DRONE_GIT_SSH_URL
- name: build
  commands:
  - cd $DRONE_REPO_NAME && sudo make
- name: report
  commands:
  - /usr/local/bin/telegram.run

node:
  machine: hangar.rcmd.space

---
kind: pipeline
type: exec
name: sandbox

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: clone
  commands:
  - git clone $DRONE_GIT_SSH_URL
- name: build
  commands:
  - cd $DRONE_REPO_NAME && sudo make seedbox
- name: failure
  commands:
  - /bin/fail
- name: report
  commands:
  - /usr/local/bin/telegram.run

node:
  machine: kind-box

---
kind: pipeline
type: exec
name: fermium

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: clone
  commands:
  - git clone $DRONE_GIT_SSH_URL
- name: build
  commands:
  - cd $DRONE_REPO_NAME && sudo make fermium
- name: report
  commands:
  - /usr/local/bin/telegram.run

node:
  machine: fermium

---
kind: pipeline
type: exec
name: printserver

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: clone
  commands:
  - git clone $DRONE_GIT_SSH_URL
- name: build
  commands:
  - cd $DRONE_REPO_NAME && sudo make printserver
- name: report
  commands:
  - /usr/local/bin/telegram.run

node:
  machine: orangepizero
