---
kind: "iac.rcmd.space/directory.v2"
id: "services.cicd.gitea.directories"
directory:
  - name: "/etc/gitea"
    ownership: "git:git"
    mode: "770"
---
kind: "iac.rcmd.space/command"
id: "services.cicd.gitea.preflight"
annotations:
  triggers:
    - "services.cicd.gitea.secrets_command"
command:
  - createCommand: "/bin/true"
    compareCommand: "test -f /etc/gitea/secrets.json"
---
kind: "iac.rcmd.space/file.v2"
id: "services.cicd.gitea.secrets_command"
annotations:
  triggers:
    - "services.cicd.gitea.secrets"
file:
  - name: "/etc/gitea/secrets.sh"
    ownership: "git:git"
    mode: "755"
    source: "stages/services/includes/cicd/templates/gitea/secrets.sh"
---
kind: "iac.rcmd.space/command"
id: "services.cicd.gitea.secrets"
annotations:
  triggers:
    - "services.cicd.gitea.config"
command:
  - createCommand: "/etc/gitea/secrets.sh"
---
kind: "iac.rcmd.space/template"
id: "services.cicd.gitea.config"
template:
  - name: "/etc/gitea/app.ini"
    template: "stages/services/includes/cicd/templates/gitea/app.ini.tmpl"
    config: "/etc/gitea/secrets.json"
    ownership: "git:git"
    mode: "640"
---
kind: "iac.rcmd.space/file.v2"
id: "services.cicd.gitea.files"
annotations:
  triggers:
    - "services.cicd.gitea.restart"
file:
  - name: "/etc/systemd/system/gitea.service"
    ownership: "root:root"
    mode: "644"
    source: "stages/services/includes/cicd/files/etc/systemd/system/gitea.service"
  - name: "/usr/local/bin/gitea-common-hook"
    ownership: "root:root"
    mode: "755"
    source: "stages/services/includes/cicd/files/usr/local/bin/gitea-common-hook"
---
kind: "iac.rcmd.space/command"
id: "services.cicd.gitea.restart"
command:
  - createCommand: "systemctl daemon-reload; systemctl enable gitea.service; systemctl restart gitea.service"
