#!/usr/bin/env bash

FIFO="/run/rbw-proxy/fifo"
API_TOKEN=$(jq '.secrets.ledger.token' /etc/secrets/secrets.json)

test -d /run/rbw-proxy || mkdir -p /run/rbw-proxy
test -p ${FIFO} && rm -f ${FIFO}
mkfifo ${FIFO}

while true; do
    INPUT=$(cat ${FIFO})
    case ${INPUT} in
        "status")
            echo "Checking Vaultwarden status"
            rbw unlocked
            STATUS=$?

            REQUEST_TOKEN=`curl -s --data-urlencode "token=${API_TOKEN}" https://api.rcmd.space/internal/token/get`
            case ${STATUS} in
                "0")
                    curl -s -H "${UA}" --data-urlencode "token=${REQUEST_TOKEN}" \
                        --data-urlencode "status=unlocked" \
                        https://api.rcmd.space/internal/vault/resolve-status
                    ;;
                *)
                    curl -s -H "${UA}" --data-urlencode "token=${REQUEST_TOKEN}" \
                        --data-urlencode "status=locked" \
                        https://api.rcmd.space/internal/vault/resolve-status
                    ;;
            esac
            ;;
    esac
done
