#!/usr/bin/env bash

counter=0

echo "Validating Vaultwarden login status"

if ! `rbw unlocked 2>/dev/null`; then
	echo "Requesting Vaultwarden login"
	export STATUS="1"
	export NAME="Vaultwarden"
	export MESSAGE="Please login"

	/etc/monitoring/notifiers/gotify.sh

	until `rbw unlocked 2>/dev/null`; do
		if test "$counter" -gt 300; then
			echo "Timed out waiting for Vaultwarden login"
			exit 1
		fi
		((counter++))
		sleep 1
	done
fi

echo "Vaultwarden successfully unlocked!"
rbw sync
