#!/usr/bin/env bash

function request_key() {
	API_TOKEN=`cat /etc/secrets/seed`

	REQUEST_TOKEN=`curl -s -XPOST --data-urlencode "token=${API_TOKEN}" https://api.rcmd.space/internal/token/get`
	KEY=${1}
	FOLDER=${2}
	OUTPUT=`curl -s -XPOST --data-urlencode "token=${REQUEST_TOKEN}" --data-urlencode "key=${KEY}" --data-urlencode "folder=${FOLDER}" https://api.rcmd.space/internal/vault/request-key`
	echo "${OUTPUT}"
}

DATA=$(request_key ${1} ${2})

STATUS=$(echo "${DATA}" | jq -r '.status')

if [ $STATUS = "200" ]; then
	echo "${DATA}" | jq -r '.data' | base64 -d
	exit 0
else
	ERROR=$(echo "${DATA}" | jq -r .data)
	echo "Failed to request a key: ${ERROR}"
	exit 1
fi
