#!/usr/bin/env bash

function request_key() {
	API_TOKEN=`jq -r '.secrets.ledger.token' /etc/secrets/secrets.json`

	REQUEST_TOKEN=`curl -s -XPOST --data-urlencode "token=${API_TOKEN}" https://api.rcmd.space/internal/token/get`
	KEY=${1}
	DIRECTORY=${2}
	OUTPUT=`curl -s -XPOST --data-urlencode "token=${REQUEST_TOKEN}" --data-urlencode "key=${KEY}" --data-urlencode "directory=${DIRECTORY}" https://api.rcmd.space/internal/vault/request-key`
	echo "${OUTPUT}"
}

DATA=$(request_key ${1} ${2})

STATUS=$(echo "${DATA}" | jq -r '.status')

if [ $STATUS = "200" ]; then
	echo "${DATA}" | jq -r '.data' | base64 -d
	exit 0
else
	echo "Failed to request a key"
	exit 1
fi
