#!/usr/bin/env bash

counter=0

function request_status() {
	API_TOKEN=`jq -r '.secrets.ledger.token' /etc/secrets/secrets.json`

	REQUEST_TOKEN=`curl -s -XPOST --data-urlencode "token=${API_TOKEN}" https://api.rcmd.space/internal/token/get`
	MACHINE_ID=`cat /etc/machine-id`
	STATUS=`curl -s -XPOST --data-urlencode "token=${REQUEST_TOKEN}" --data-urlencode "machine-id=${MACHINE_ID}" -o /dev/null -w "%{http_code}" https://api.rcmd.space/internal/vault/request-lock`
	echo "${STATUS}"
}

echo "Requesting Vaultwarden lock"
VAULT_STATUS=`request_status`
if [ ${VAULT_STATUS} = "200" ]; then
	echo "Vaultwarden successfully locked!"
else
	echo "Vaultwarden lock requested, but received API status is ${VAULT_STATUS}"
done

