---
kind: "iac.rcmd.space/package"
id: "packages.server"
package:
  - name: "cowsay"
  - name: "aha"
  - name: "cryptsetup"
  - name: "duplicity"
  - name: "docker-registry"
  - name: "gnuplot"
  - name: "gocryptfs"
  - name: "gridsite-clients"
  - name: "html2text"
  - name: "imagemagick"
  - name: "inotify-tools"
  - name: "mosh"
  - name: "ffmpeg"
  - name: "nfs-common"
  - name: "libimage-exiftool-perl"
  - name: "lua-dbi-mysql"
  - name: "pandoc"
  - name: "texlive-latex-base"
  - name: "texlive-fonts-recommended"
  - name: "texlive-latex-recommended"
  - name: "texlive-latex-extra"
  - name: "trivy"
  - name: "lmodern"
  - name: "percona-toolkit"
  - name: "postfix"
  - name: "radicale"
  - name: "podman"
  - name: "python3-full"
  - name: "python3-bcrypt"
  - name: "python3-passlib"
  - name: "python3-tqdm"
  - name: "pup"
  - name: "id3v2"
  - name: "telnet"
  - name: "tree"
  - name: "zip"
  - name: "redis"
  - name: "webdis"
