---
kind: "iac.rcmd.space/package"
id: "packages.essentials"
package:
  - name: "at"
  - name: "bc"
  - name: "htop"
  - name: "bash-completion"
  - name: "dnsutils"
  - name: "curl"
  - name: "davfs2"
  - name: "dialog"
  - name: "markdown"
  - name: "iptables-persistent"
  - name: "needrestart"
  - name: "python3-venv"
  - name: "reptyr"
  - name: "screen"
  - name: "sudo"
  - name: "sqlite3"
  - name: "sshfs"
  - name: "tinc"
  - name: "uuid-runtime"
  - name: "unattended-upgrades"
  - name: "vim"
  - name: "whois"
  - name: "neovim"
  - name: "pv"
