---
kind: "iac.rcmd.space/template"
id: "services.nginx.sites.config"
annotations:
  triggers:
    - "services.nginx.test"
    - "services.nginx.reload"
template:
  - name: "/etc/nginx/sites-available/ci-ng.conf"
    template: "stages/services/includes/nginx/templates/nginx/sites/ci.conf.tmpl"
    config: "variables/main.json"
    mode: "644"
    ownership: "root:root"
---
kind: "iac.rcmd.space/symlink"
id: "services.nginx.sites.link"
symlink:
  - name: "/etc/nginx/sites-enabled/ci-ng.conf"
    mode: "777"
    ownership: "root:root"
    source: "/etc/nginx/sites-available/ci-ng.conf"
